[package]
name = "rust-foundations"
version = "0.1.0"
edition = "2021"

default-run = "rust-foundations"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
